name: CI — docker-compose tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PAT }}

      - name: Checkout user_service repo
        uses: actions/checkout@v4
        with:
          repository: Ingenieria-Web-2/user_service
          path: user_service
          token: ${{ secrets.CI_PAT }}

      - name: Checkout recipe_service repo
        uses: actions/checkout@v4
        with:
          repository: Ingenieria-Web-2/recipe_service
          path: recipe_service
          token: ${{ secrets.CI_PAT }}

      - name: Login to Docker Hub (for binfmt image pulls)
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PAT }}

      - name: Try to pull published images
        run: |
          docker pull ghcr.io/ingenieria-web-2/user_service:latest || true
          docker pull ghcr.io/ingenieria-web-2/recipe_service:latest || true

      - name: Build user_service images with cache
        uses: docker/build-push-action@v5
        with:
          context: ./user_service
          file: ./user_service/Dockerfile
          push: false
          tags: ghcr.io/ingenieria-web-2/user_service:latest
          cache-from: type=registry,ref=ghcr.io/ingenieria-web-2/user_service:latest
          cache-to: type=registry,ref=ghcr.io/ingenieria-web-2/user_service:cache,mode=max

      - name: Build recipe_service image with cache
        uses: docker/build-push-action@v5
        with:
          context: ./recipe_service
          file: ./recipe_service/Dockerfile
          push: false
          tags: ghcr.io/ingenieria-web-2/recipe_service:latest
          cache-from: type=registry,ref=ghcr.io/ingenieria-web-2/recipe_service:latest
          cache-to: type=registry,ref=ghcr.io/ingenieria-web-2/recipe_service:cache,mode=max

      - name: Build docker-compose images (fallback)
        run: docker compose -f "$GITHUB_WORKSPACE/docker-compose.yaml" build --parallel || true

      - name: Start DB services
        run: docker compose -f "$GITHUB_WORKSPACE/docker-compose.yaml" up -d user_db recipe_db

      - name: Wait for user_db to be ready
        run: |
          echo "Waiting for Postgres (user_db)..."
          docker compose -f "$GITHUB_WORKSPACE/docker-compose.yaml" exec user_db bash -c 'until pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do sleep 1; done'
        env:
          POSTGRES_USER: user
          POSTGRES_DB: user_db

      - name: Wait for recipe_db to be ready
        run: |
          echo "Waiting for Postgres (recipe_db)..."
          docker compose -f "$GITHUB_WORKSPACE/docker-compose.yaml" exec recipe_db bash -c 'until pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do sleep 1; done'
        env:
          POSTGRES_USER: user
          POSTGRES_DB: recipe_db

      - name: Run user_service tests
        run: |
          # Ensure the reports directory exists inside the mounted app folder so pytest output
          # written by the container is visible on the runner (the service mounts ./user_service/app).
          mkdir -p user_service/app/reports
          docker compose -f "$GITHUB_WORKSPACE/docker-compose.yaml" run --rm user_service python -m pytest --junitxml=user_service/app/reports/users-results.xml -q

      - name: Run recipe_service tests
        run: |
          mkdir -p recipe_service/app/reports
          docker compose -f "$GITHUB_WORKSPACE/docker-compose.yaml" run --rm recipe_service python -m pytest --junitxml=recipe_service/app/reports/recipes-results.xml -q

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          # capture any reports generated under service folders
          path: '**/reports/*.xml'

      - name: Collect container logs
        if: always()
        run: |
          mkdir -p logs
          docker compose -f "$GITHUB_WORKSPACE/docker-compose.yaml" logs user_service > logs/user_service.log || true
          docker compose -f "$GITHUB_WORKSPACE/docker-compose.yaml" logs recipe_service > logs/recipe_service.log || true
        continue-on-error: true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: service-logs
          path: logs/**

      - name: Tear down
        if: always()
        run: docker compose -f "$GITHUB_WORKSPACE/docker-compose.yaml" down -v

      - name: Debug workspace layout
        if: always()
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -la "$GITHUB_WORKSPACE" || true
